Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 8
  end

  config.vm.provision "file", source: "./", destination: "$HOME/immortals_root"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    cd ~/immortals_root/shared/utils
    ./install.sh --ll-mode
  SHELL
end
