Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 8
  end

  config.vm.provision "file", source: "./", destination: "$HOME/immortals_root"

  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3.5
    cd ~/immortals_root/harness
    ./prepare_setup.sh --installation-dir ~/.immortals
    ./setup.sh
    cp immortalsrc ~/.immortalsrc
    cd ~/immortals_root
    ./gradlew deploy
  SHELL
end
