@startuml

participant "immortals"
participant "knowledge-repo"

participant "shared/modules"
participant "dsl/resource-dsl"
participant "das/das-service"

participant "applications/clients/ATAKLite"
participant "applications/server/Marti"
participant "applications/clients/AnalysisRunner"


"immortals" -> "knowledge-repo": buildAdsl() [maven]
"knowledge-repo" -> "immortals": finished

"immortals" -> "shared/modules": buildAndPubishModules [gradle composite build]

note over "shared/modules"
    I already have some build scripts
    being used in the buildSrc (typical)
    folder in this project to minimize
    the work necessary to make new DFUs
    which is probably where you might want
    to put yours
end note
"shared/modules" -> "shared/modules": buildGradlePlugins
"shared/modules" -> "shared/modules": buildModules
"shared/modules" -> "shared/modules": publishModules
"shared/modules" -> "immortals": finished

"immortals" -> "knowledge-repo": buildKnowledgeRepository [maven]
"knowledge-repo" -> "immortals": finished

"immortals" -> "dsl/resource-dsl": build [stack]
"dsl/resource-dsl" -> "immortals": finished

"immortals" -> "applications/clients/ATAKLite": buildBaselineApplication [gradle composite build]
"applications/clients/ATAKLite" -> "immortals": finished

"immortals" -> "applications/server/Marti": buildBaselineApplication [gradle composite build]
"applications/server/Marti" -> "immortals": finished

"immortals" -> "applications/clients/AnalysisRunner": build [gradle composite build]
"applications/clients/AnalysisRunner" -> "immortals": finished

@enduml