#!/bin/bash


# export SESSION_ID="session-$(uuidgen)"
export SESSION_ID="I$(date +%s000)"


### End user notes
# The example invocations below use all possible configurable 'knobs'.  To run
# CP1 or CP2 *only*, we will set reasonable defaults for the 'knobs' associated
# with the other CP.
# For testing CP1 specifically, use the following defaults for CP2 settings:
#     --pli-client-msg-rate 10 \
#     --image-client-msg-rate 10 \
#     --server-bandwidth 2000 \
#     --client-device-count 2 \
#
# For testing CP2 specifically, use the following defaults for the CP1 settings:
#     --android-bluetooth-resource yes \
#     --android-usb-resource yes \
#     --android-internal-gps-resource yes \
#     --android-ui-resource yes \
#     --gps-satellite-resource yes \
#     --mission-trusted-comms no



# This example generates a CP2 perturbation input file
# The session identifier is generated by the script.
python3 ./py/mission_perturb.py \
     --session ${SESSION_ID} \
     --output deployment_model.ttl \
     --template ./template/gme-template.ttl \
     --pli-client-msg-rate 60 \
     --image-client-msg-rate 2 \
     --server-bandwidth 1000 \
     --client-device-count 2 \
     --android-bluetooth-resource yes \
     --android-usb-resource yes \
     --android-internal-gps-resource yes \
     --android-ui-resource yes \
     --gps-satellite-resource yes \
     --mission-trusted-comms yes

# This shows how to post a perturbation file to the DAS-server
curl -H "Content-Type:text/plain" \
     -X POST \
     --data-binary @deployment_model.ttl \
     http://localhost:8080/bbn/das/deployment-model

# Run the simulation
# THe first five parameters are mandatory
# The ones following that indicate the presence of a resource or requirement,
# and their omission indicates they are not present in the mission model
python2 ../../harness/scenarioconductor/scenarioconductor.py \
    --sessionidentifier ${SESSION_ID} \
    --clientcount 2 \
    --serverbandwidth 1000 \
    --clientimagesendfrequency 2 \
    --clientmsgsendfrequency 60 \
    --android-bluetooth-resource \
    --android-usb-resource \
    --android-internal-gps-resource \
    --android-ui-resource \
    --gps-satellite-resource \
    --mission-trusted-comms

# Prepare and run subsequent tests
