package com.securboration.immortals.ontology.constraint;


public enum PropertyCriterionType {
    
    WHEN_PROPERTY_PRESENT,
    WHEN_PROPERTY_ABSENT,

    WHEN_PROPERTY_GREATER_THAN_EXCLUSIVE,
    WHEN_PROPERTY_GREATER_THAN_INCLUSIVE,
    WHEN_PROPERTY_LESS_THAN_EXCLUSIVE,
    WHEN_PROPERTY_LESS_THAN_INCLUSIVE,
    WHEN_PROPERTY_EQUALS,
    WHEN_PROPERTY_NOT_EQUALS,
    
    WHEN_PROPERTY_ADDED,
    WHEN_PROPERTY_REMOVED,
    
    WHEN_PROPERTY_UNCHANGED,
    WHEN_PROPERTY_CHANGES,
    WHEN_PROPERTY_INCREASES,
    WHEN_PROPERTY_DECREASES,
    WHEN_PROPERTY_MINIMIZED,
    WHEN_PROPERTY_MAXIMIZED,
    
}
