package com.securboration.immortals.ontology.constraint;


public enum PropertyCriterionType {
    
    PROPERTY_PRESENT,
    PROPERTY_ABSENT,

    PROPERTY_GREATER_THAN_EXCLUSIVE,
    PROPERTY_GREATER_THAN_INCLUSIVE,
    PROPERTY_LESS_THAN_EXCLUSIVE,
    PROPERTY_LESS_THAN_INCLUSIVE,
    PROPERTY_EQUALS,
    PROPERTY_NOT_EQUALS,
    
    PROPERTY_ADDED,
    PROPERTY_REMOVED,
    
    PROPERTY_UNCHANGED,
    PROPERTY_CHANGES,
    PROPERTY_INCREASES,
    PROPERTY_DECREASES,
    PROPERTY_MINIMIZED,
    PROPERTY_MAXIMIZED,
    
}
