XSL_GENERATION_EXTRA_COMMENT = """
  Description:
     Stylesheet that generates XHTML documentation, given an XML
     Schema document
  Assumptions:
     -Resulting documentation will only be displayed properly with
      the latest browsers that support XHTML and CSS. Older
      browsers are not supported.
     -Assumed that XSD document conforms to the XSD recommendation.
      No validity checking is done.
  Constraints:
     -Local schema components cannot contain two dashes in
      'documentation' elements within their 'annotation' element.
      This is because the contents of those 'documentation'
      elements are displayed in a separate window using Javascript.
      This Javascript code is enclosed in comments, which do not
      allow two dashes inside themselves.
  Notes:
     -Javascript code is placed within comments, even though in
      strict XHTML, JavaScript code should be placed within CDATA
      sections. This is because current browsers generate a syntax
      error if the page contains CDATA sections. Placing Javascript
      code within comments means that the code cannot contain two
      dashes.
      (See 'PrintJSCode' named template.)
"""

HTML_NS = "http://www.w3.org/1999/xhtml"
XSL_NS = "http://www.w3.org/1999/XSL/Transform"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"

# Default values for primitive data types
PRIMITIVE_TYPES_DEFAULT = {
    'boolean': 'true',
    'float': '9999',
    'double': '9999',
    'decimal': '9999',
    'integer': '9999',
    'string': 'autogenerated',
    'normalizedString': 'autogenerated',
    'token': 'autogenerated',
    'long': '9999',
    'nonPositiveInteger': '-9999',
    'nonNegativeInteger': '9999',
    'int': '9999',
    'short': '9999',
    'unsignedInt': '9999',
    'unsignedShort': '9999',
    'unsignedLong': '9999',
    'positiveInteger': '9999',
    'date': '2000-01-01',
    'time': '00:00:00',
    'dateTime': '2000-01-01T00:00:00',
}

# Always use lowercase to improve name match
SIMPLE_TYPES_DEFAULT = {
    'ipv6address': '2001:db8:85a3:8d3:1319:8a2e:370:7348',
    'ipv4address': '127.0.0.1',
    'ipaddress': '127.0.0.1',
}
