name: aql
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - certifi=2018.11.29=py36_0
  - click=7.0=py36_0
  - flask=1.0.2=py36_1
  - itsdangerous=1.1.0=py36_0
  - jinja2=2.10=py36_0
  - markupsafe=1.1.0
  - openssl=1.1.1
  - werkzeug=0.14.1=py36_0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - ncurses=6.1
  - pip=18.1=py36_0
  - python=3.6.7
  - readline=7.0
  - setuptools=40.6.2=py36_0
  - sqlite=3.25.3
  - tk=8.6.8
  - wheel=0.32.3=py36_0
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - filehash==0.1.dev3
    - lxml==4.3.0

#prefix: /home/elmarce/miniconda3/envs/aql

